Demo_01_reborn/urls.py
from django.contrib import admin
from django.urls import path, include
from Users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Food.urls")),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='Users/logout.html'), name="logout"),
    path('profile/', user_views.profile, name="profile"),

]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Food/urls.py
from django.urls import path
from . import views

app_name = 'Food'
urlpatterns = [
    # /
    # path('', views.index, name='index'),
    path('', views.IndexClassView.as_view(), name='index'),
    # /item/
    # path("item/", views.item, name='item'),
    # /item_id/
    # path("<int:item_id>", views.details, name='details'),
    path('<int:pk>/', views.DetailClassView.as_view(), name='details'),
    # add items
    # path("add", views.create_item, name='create_item'),
    path("add", views.CreateItem.as_view(), name='create_item'),
    # edit items
    path("update/<int:item_id>", views.update_item, name='update_item'),
    # delete items
    path("delete/<int:item_id>", views.delete_item, name='delete_item'),

]

Users/urls.py
from django.urls import path

urlpatterns = [

]

Food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.


class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=100)
    item_description = models.CharField(max_length=100, blank=True)
    item_price = models.IntegerField()
    item_quantity = models.IntegerField()
    # item_image = models.ImageField(upload_to='')
    item_image = models.CharField(max_length=500,
                                  default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('Food:details', kwargs={'pk': self.pk})

Users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user_name = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    birth_date = models.DateField()
    phone_number = models.CharField(max_length=20, blank=True)
    image = models.ImageField(upload_to='profile_pics', default='profile_pics.jpg')
    address = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user_name.username

Food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        # fields = ['item_name', 'item_description', 'item_price', 'item_quantity', 'item_image']

Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Food/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from .forms import ItemForm
from .models import Item
# from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.


# Class based views:
class IndexClassView(ListView):
    model = Item
    template_name = 'Food/index.html'
    context_object_name = 'item_list'


class DetailClassView(DetailView):
    model = Item
    template_name = 'Food/details.html'
    context_object_name = 'item'


class CreateItem(CreateView):
    model = Item
    fields = '__all__'
    template_name = 'Food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

# Function based views:
# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, 'Food/index.html', context)
#
#
# def details(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item
#     }
#     return render(request, 'Food/details.html', context)


# def create_item(request):
#     form = ItemForm(request.POST or None)
#     context = {
#         'form': form,
#     }
#     if form.is_valid():
#         form.save()
#         return redirect('Food:index')
#     return render(request, 'Food/item-form.html', context)


def update_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    form = ItemForm(request.POST or None, instance=item)
    context = {
        'form': form,
        'item_id': item_id,
    }
    if form.is_valid():
        form.save()
        return redirect('Food:index')
    return render(request, 'Food/item-form.html', context)


def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    if request.method == 'POST':
        item.delete()
        return redirect('Food:index')
    return render(request, 'Food/item-delete.html', context)

Users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('user_name')
            messages.success(request, f'Welcome {user_name}! Your account has been created successfully!')
            return redirect('login')
    else:
        form = RegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'Users/register.html', context)


@login_required
def profile(request):
    return render(request, 'Users/profile.html')

templates/Food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#    <link rel="stylesheet" href="{% static 'Food/style.css' %}">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    </script>
    <title>Title</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark-subtle">
        <a class="navbar-brand btn btn-outline-secondary" href="{% url 'Food:index' %}">Food</a>
        <div class="navbar navbar-dark">
            <a class="nav-item btn btn-outline-secondary" href="{% url 'Food:create_item' %}">Add Item</a>
            <a class="nav-item btn btn-outline-secondary" href="#">Edit Item</a>
            <a class="nav-item btn btn-outline-secondary text-bg-warning" href="#">Delete Item</a>
            
            {% if user.is_authenticated %}
                <form method="post" action="/logout/">
                    {% csrf_token %}
                    <button class="btn btn-outline-secondary">Log Out</button>
                </form>
                <a class="btn btn-outline-secondary" href="{% url 'profile' %}">Profile</a>
            {% else %}
            	<a class="btn btn-outline-secondary" href="{% url 'login' %}">Log In</a>
                <a class="btn btn-outline-secondary" href="{% url 'register' %}">Sign Up</a>
            {% endif %} 
        </div>
    </nav>

    {% if message %}
        {% for msg in message %}
            <div class="alert alert-{{ msg.tags }}">{{ msg }}</div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

templates/Food/details.html
{% extends "Food/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
</head>
<body>
    {% block body %}
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-2" >
                    <img class="card" height="450px" width="350" src="{{ item.item_image }}" alt=""/>
                </div>
                <div class="col-md-6">
                    <h2>{{ item.item_name }}</h2>
                    <h3>{{ item.item_description }}</h3>
                    <h4>BDT {{ item.item_price }}/-</h4>
                    <a href="{% url 'Food:delete_item' item.id %}">Delete</a>
                    <a href="https://www.bkash.com/products-services/payment" class="btn btn-danger">Order Now</a>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

templates/Food/index.html
{% extends "Food/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
</head>
<body>
    {% block body %}
        {% for item in item_list %}
        	<div class="row">
                <div class="col-sm-2 offset-md-2">
                    <img class="card" height="250px" width="200px" src="{{ item.item_image }}" alt="">
                </div>
                <div class="col-md-4">
                    <h3>This is "{{ item.item_name }}"</h3>
                    <h4>It's offered with "{{ item.item_description }}"</h4>
                    <h5>Item Price = BDT {{ item.item_price }}/-</h5>
                    <h6>This item was added by: {{ item.user_name.first_name }} {{ item.user_name.last_name }}</h6>
                </div>
                <div class="col-sm-1">
                    <a href="{% url 'Food:details' item.id %}" class="btn btn-success">Details</a>
                </div>
            </div>
        {% endfor %}
    {% endblock %}
</body>
</html>




{# Below is the older codes. Updated codes are mentioned above #}
<!--
{#{% extends "Food/base.html" %}#}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
</head>
<body>
{#    {% block body %}#}
{#        {% for item in item_list %}#}
        	<ul>
                <li>
{#                    <a href="{% url 'Food:details' item.id %}">{{ item.item_name }}</a>#}
                </li>
            </ul>
{#        {% endfor %}#}
{#    {% endblock %}#}
</body>
</html>
-->

templates/Food/item-delete.html
{% extends 'Food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete Item</title>
</head>
<body>
    {% block body %}
        <form method="POST">
            {% csrf_token %}
            <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
            <button type="submit">Confirm</button>
        </form>
    {% endblock %}
</body>
</html>

templates/Food/item-form.html
{% extends "Food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Item Form</title>
</head>
<body>
    {% block body %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Save</button>
        </form>
    {% endblock %}
</body>
</html>

templates/Users/login.html
{% extends "Food/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LogIn</title>
</head>
<body>
    {% block body %}
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4">
                    <div class="card">
                        <div class="card-header text-white bg-info">
                            <div class="card-title">Log In</div>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
{#                                {{ form }}#}
                                {% for field in form %}
                                	<div class="col-form-label-lg">
                                        {{ field.name }}
                                        {{ field }}
                                    </div>
                                {% endfor %}
                                <button class="bg-info" type="submit">Log In</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

templates/Users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LogOut</title>
</head>
<body>
    <h1>You have been logged out successfully!</h1>
</body>
</html>

templates/Users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profile</title>
</head>
<body>
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url }}" height="100px" width="100px" alt="">
</body>
</html>

templates/Users/register.html
{% extends 'Food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Form</title>
</head>
<body>
    {% block body %}
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4">
                    <div class="card">
                        <div class="card-header text-white bg-info">
                            <div class="card-title">Sign Up</div>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
{#                                {{ form }}#}
                                {% for field in form %}
                                    <div class="col-form-label-lg">
                                	    {{ field.name }}
                                        {{ field }}
                                    </div>
                                {% endfor %}
                                <button class="bg-info" type="submit">Sign Up</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
    
</body>
</html>